/* eslint-disable */
const guildData = [
  {
    id: 0,
    guildServer: '니나브',
    guildName: '모코코야왜또칭얼거려',
    guildKinds: '친목',
    guildShopLevel: '5',
    guildLevelLimit: '1475',
    guildAgeLimit: '20',
    guildDiscord: '필수',
    guildDiscordMike: '자유',
    guildKakaoTalk: '선택',
    guildContent: '학원팟',
    guildContentRagne: '발탄노말~일리하드',
    guildSubjugation: '선택',
    guildOccupationWar: '선택',
    guildContactLink: 'https://www.naver.com',
  },
  {
    id: 1,
    guildServer: '카단',
    guildName: '모코코는누구야',
    guildKinds: '친목',
    guildShopLevel: '5',
    guildLevelLimit: '1475',
    guildAgeLimit: '24',
    guildDiscord: '필수',
    guildDiscordMike: '자유',
    guildKakaoTalk: '선택',
    guildContent: '학원팟',
    guildContentRagne: '발탄노말~아브하드',
    guildSubjugation: '선택',
    guildOccupationWar: '선택',
    guildContactLink: 'https://www.naver.com',
  },
  {
    id: 3,
    guildServer: '아브렐슈드',
    guildName: '모코코야뭐해',
    guildKinds: '친목',
    guildShopLevel: '5',
    guildLevelLimit: '1475',
    guildAgeLimit: '26',
    guildDiscord: '필수',
    guildDiscordMike: '자유',
    guildKakaoTalk: '선택',
    guildContent: '학원팟',
    guildContentRagne: '발탄노말~쿠크노말',
    guildSubjugation: '선택',
    guildOccupationWar: '선택',
    guildContactLink: 'https://www.naver.com',
  },
  {
    id: 4,
    guildServer: '니나브',
    guildName: '모코코는코코해',
    guildKinds: '친목',
    guildShopLevel: '5',
    guildLevelLimit: '1475',
    guildAgeLimit: '30',
    guildDiscord: '필수',
    guildDiscordMike: '자유',
    guildKakaoTalk: '선택',
    guildContent: '학원팟',
    guildContentRagne: '발탄노말~비하하드',
    guildSubjugation: '선택',
    guildOccupationWar: '선택',
    guildContactLink: 'https://www.naver.com',
  },
];

export default guildData;
